services:
  - type: web
    name: power-loss-calculator
    env: docker
    repo: https://github.com/kakafuAI/power-loss-calculator
    branch: master
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: RENDER
        value: "true"
